language: ruby
rvm:
- 2.6.1
env:
- DB=pgsql
services:
- postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: 4f737394-5a0d-47d4-9c29-9957eed05f32
  app: utbmprojet1
  on:
    repo: Swyfee/Projet-1
run: "rails db:migrate"