development:
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  username: postgres
  password: '0506'

test:
  adapter: postgresql
  database: travis_ci_test

production:
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  username: postgres
  password: '0506'