development:
  adapter: postgresql
  encoding: utf8
  database: postgres
  username: postgres
  host: db

test:
  adapter: postgresql
  encoding: utf8
  database: postgres
  username: postgres
  password: '0506'

production:
  adapter: postgresql
  encoding: utf8
  database: postgres
  username: postgres
  password: '0506'