development:
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  username: postgres
  password: '0506'

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  username: postgres
  password: '0506'

production:
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  username: postgres
  password: '0506'